services:

  mongodb:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped      
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=takween_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGHOST=localhost
      - PGPORT=5432



volumes:
  mongodb-data:
  postgres-data: